-- SILVER_AP_INVOICES: PRD Update (Baan + Workday onboarding)
-- Sources: sample_business_requirements_source_onboarding.csv,
--          sample_business_requirements_column_mapping.csv,
--          sample_business_requirements_business_rules.csv
-- Generated: 2026-05-16
--
-- Changes from prior version:
--   - Added Baan IV UNION ALL branch with dedup (BR-003)
--   - Added Workday UNION ALL branch
--   - Extended status CASE to handle POSTED, Approved, In Review (BR-001)
--   - Payment terms: pass-through for Baan/Workday (pending OQ-1 decision)
--
-- Assumptions requiring engineering review:
--   1. Oracle payment terms remain normalized (NET30/NET60) while Baan (N30/N60)
--      and Workday (Net 30/Net 60) are raw. Inconsistent until BR-005 is resolved.
--   2. Baan dedup applies only to Baan branch (not global).
--   3. TARGET_LAG stays at 1 minute until Gold DT exists (then switch to DOWNSTREAM).
--   4. UPPER() used defensively for status matching in case of future case drift.

CREATE OR REPLACE DYNAMIC TABLE COCO_WORKSHOP.PIPELINE_LAB.SILVER_AP_INVOICES
  TARGET_LAG = '1 minute'
  WAREHOUSE = COMPUTE_WH
  REFRESH_MODE = INCREMENTAL
  COMMENT = 'Silver AP Invoices: unified SAP + Oracle + Baan + Workday with normalized status'
AS
SELECT
    INVOICE_ID,
    INVOICE_NUMBER,
    VENDOR_ID,
    VENDOR_NAME,
    INVOICE_DATE,
    DUE_DATE,
    INVOICE_AMOUNT,
    CURRENCY_CODE,
    PAYMENT_TERMS,
    PO_NUMBER,
    LINE_DESCRIPTION,
    GL_ACCOUNT,
    COST_CENTER,
    CASE 
        WHEN UPPER(APPROVAL_STATUS) IN ('APPROVED', 'VALIDATED', 'POSTED') THEN 'APPROVED'
        WHEN UPPER(APPROVAL_STATUS) IN ('PENDING', 'IN REVIEW') THEN 'PENDING'
        ELSE 'OTHER'
    END AS APPROVAL_STATUS,
    CREATED_AT,
    SOURCE_SYSTEM
FROM (
    -- SAP branch
    SELECT
        INVOICE_ID,
        INVOICE_NUMBER,
        VENDOR_ID,
        VENDOR_NAME,
        INVOICE_DATE,
        DUE_DATE,
        INVOICE_AMOUNT,
        CURRENCY_CODE,
        PAYMENT_TERMS,
        PO_NUMBER,
        LINE_DESCRIPTION,
        GL_ACCOUNT,
        COST_CENTER,
        APPROVAL_STATUS,
        CREATED_AT,
        'SAP' AS SOURCE_SYSTEM
    FROM COCO_WORKSHOP.SOURCE_DATA.BRONZE_SAP_AP_INVOICES

    UNION ALL

    -- Oracle branch (payment terms normalized — see OQ-1)
    SELECT
        INV_ID AS INVOICE_ID,
        INV_NUM AS INVOICE_NUMBER,
        SUPPLIER_ID AS VENDOR_ID,
        SUPPLIER_NAME AS VENDOR_NAME,
        INV_DATE AS INVOICE_DATE,
        PAYMENT_DUE_DATE AS DUE_DATE,
        TOTAL_AMOUNT AS INVOICE_AMOUNT,
        CURRENCY AS CURRENCY_CODE,
        CASE 
            WHEN TERMS_CODE = 'N30' THEN 'NET30'
            WHEN TERMS_CODE = 'N60' THEN 'NET60'
            ELSE TERMS_CODE
        END AS PAYMENT_TERMS,
        PURCHASE_ORDER AS PO_NUMBER,
        DESCRIPTION AS LINE_DESCRIPTION,
        ACCOUNT_CODE AS GL_ACCOUNT,
        DEPT_CODE AS COST_CENTER,
        STATUS AS APPROVAL_STATUS,
        CREATION_DATE AS CREATED_AT,
        'ORACLE' AS SOURCE_SYSTEM
    FROM COCO_WORKSHOP.SOURCE_DATA.BRONZE_ORACLE_AP_INVOICES

    UNION ALL

    -- Baan branch with dedup per BR-003
    SELECT
        BAN_INVOICE_ID AS INVOICE_ID,
        BAN_INVOICE_REF AS INVOICE_NUMBER,
        BAN_VENDOR_CODE AS VENDOR_ID,
        BAN_VENDOR_DESC AS VENDOR_NAME,
        BAN_INV_DATE AS INVOICE_DATE,
        BAN_PAY_DATE AS DUE_DATE,
        BAN_AMOUNT AS INVOICE_AMOUNT,
        BAN_CURR AS CURRENCY_CODE,
        BAN_PAY_TERMS AS PAYMENT_TERMS,
        BAN_PO_REF AS PO_NUMBER,
        BAN_LINE_DESC AS LINE_DESCRIPTION,
        BAN_GL_CODE AS GL_ACCOUNT,
        BAN_COST_CTR AS COST_CENTER,
        BAN_STATUS AS APPROVAL_STATUS,
        BAN_CREATED AS CREATED_AT,
        'BAAN' AS SOURCE_SYSTEM
    FROM COCO_WORKSHOP.SOURCE_DATA.BRONZE_BAAN_AP_INVOICES
    QUALIFY ROW_NUMBER() OVER (PARTITION BY BAN_INVOICE_REF ORDER BY BAN_CREATED DESC) = 1

    UNION ALL

    -- Workday branch
    SELECT
        WD_INVOICE_ID AS INVOICE_ID,
        WD_INVOICE_NUM AS INVOICE_NUMBER,
        WD_SUPPLIER_ID AS VENDOR_ID,
        WD_SUPPLIER_NAME AS VENDOR_NAME,
        WD_INVOICE_DATE AS INVOICE_DATE,
        WD_DUE_DATE AS DUE_DATE,
        WD_AMOUNT AS INVOICE_AMOUNT,
        WD_CURRENCY AS CURRENCY_CODE,
        WD_PAY_TERMS AS PAYMENT_TERMS,
        WD_PO_NUMBER AS PO_NUMBER,
        WD_MEMO AS LINE_DESCRIPTION,
        WD_LEDGER_ACCOUNT AS GL_ACCOUNT,
        WD_COST_CENTER AS COST_CENTER,
        WD_APPROVAL_STATUS AS APPROVAL_STATUS,
        WD_CREATED_DATE AS CREATED_AT,
        'WORKDAY' AS SOURCE_SYSTEM
    FROM COCO_WORKSHOP.SOURCE_DATA.BRONZE_WORKDAY_AP_INVOICES
);


-- ============================================================
-- VALIDATION QUERIES
-- ============================================================

-- 1. Record counts by source (expect SAP:15, ORACLE:15, BAAN:<=10, WORKDAY:10)
SELECT SOURCE_SYSTEM, COUNT(*) AS RECORD_COUNT
FROM COCO_WORKSHOP.PIPELINE_LAB.SILVER_AP_INVOICES
GROUP BY SOURCE_SYSTEM
ORDER BY SOURCE_SYSTEM;

-- 2. Status normalization (should only produce APPROVED, PENDING, or OTHER)
SELECT APPROVAL_STATUS, SOURCE_SYSTEM, COUNT(*) AS CNT
FROM COCO_WORKSHOP.PIPELINE_LAB.SILVER_AP_INVOICES
GROUP BY APPROVAL_STATUS, SOURCE_SYSTEM
ORDER BY APPROVAL_STATUS, SOURCE_SYSTEM;

-- 3. Baan dedup verification (Silver count <= Bronze count)
SELECT 
    (SELECT COUNT(*) FROM COCO_WORKSHOP.SOURCE_DATA.BRONZE_BAAN_AP_INVOICES) AS BAAN_BRONZE_COUNT,
    (SELECT COUNT(*) FROM COCO_WORKSHOP.PIPELINE_LAB.SILVER_AP_INVOICES WHERE SOURCE_SYSTEM = 'BAAN') AS BAAN_SILVER_COUNT;

-- 4. NULL check on required fields (all should be 0)
SELECT SOURCE_SYSTEM, 
    COUNT_IF(INVOICE_ID IS NULL) AS NULL_INVOICE_ID,
    COUNT_IF(VENDOR_NAME IS NULL) AS NULL_VENDOR_NAME,
    COUNT_IF(INVOICE_AMOUNT IS NULL) AS NULL_AMOUNT,
    COUNT_IF(CURRENCY_CODE IS NULL) AS NULL_CURRENCY
FROM COCO_WORKSHOP.PIPELINE_LAB.SILVER_AP_INVOICES
GROUP BY SOURCE_SYSTEM
ORDER BY SOURCE_SYSTEM;

-- 5. Payment terms distribution (review for OQ-1 consistency decision)
SELECT SOURCE_SYSTEM, PAYMENT_TERMS, COUNT(*) AS CNT
FROM COCO_WORKSHOP.PIPELINE_LAB.SILVER_AP_INVOICES
GROUP BY SOURCE_SYSTEM, PAYMENT_TERMS
ORDER BY SOURCE_SYSTEM, PAYMENT_TERMS;
